config/routes.rb
Rails.application.routes.draw do

  resources :search_suggestions, only: [:new, :create]

  resources :collaborations, only: [:create,:edit,:destroy]

  resources :downgrades, only: :create

  resources :charges, only: [:new,:create,:destroy]

  resources :wikis

  devise_for :users

  root 'wikis#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy
  has_many :wiki_collaborators, through: :collaboration, source: :wiki

  after_initialize { self.role ||= :standard }
  after_update :publish_wikis

  validates :encrypted_password, presence: true, length: { minimum: 6 }
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

  enum role: [:standard,:premium,:admin]

  def self.search(term)
    where('LOWER(title) LIKE :term', term: "%#{term.downcase}%")
  end

  def downgrade
    self.standard!
  end

  private
  def publish_wikis
    if self.standard?
      self.wikis.each do |wiki|
        wiki.update_attributes(private: false)
      end
    end
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  after_update :initialize_wiki, except: :new

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true



  private
  def initialize_wiki
    self.private ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :authenticate_user!
  include Pundit

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "BigMoney Membership - #{current_user.email}",
    amount: 10_00
  }
end

  def create
    customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   charge = Stripe::Charge.create(
     customer: customer.id,
     amount: 10_00,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )

   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   current_user.premium!
   redirect_to root_path

   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  def create
    @wiki = Wiki.find(params[:wiki_id])
    selected_emails = params[:selected_emails]
    unless selected_emails
      flash[:notice] = "Please check at least one user"
      redirect_back(fallback_location: @wiki)
      return
    else
      selected_emails.each do |email|
        user = User.find_by(email: email)
        Collaboration.create(user: user, wiki: @wiki)
    end
 end
    flash[:notice] = "The collaboration(s) were created"
    redirect_to @wiki
  end

  def edit
    @colabs = Collaboration.all
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    selected_emails = params[:selected_emails]
    unless selected_emails
      flash[:notice] = "Please check at least one user"
      redirect_back(fallback_location: @wiki)
      return
    else
      selected_emails.each do |email|
        user = User.find_by(email: email)
        colab = Collaboration.find_by(user: user.id, wiki: @wiki)
        colab.destroy
       end
    end
    flash[:notice] = "The collaboration(s) were removed"
    redirect_to @wiki
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def create
    current_user.standard!
    redirect_to root_path, notice: "You are now a standard-tier user"
  end
end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController
  def create
    current_user.downgrade
    redirect_to root_path, notice: "You are now a standard-tier user"
  end
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  def new
    current_collaborator_emails = []
    current_collaborator_emails << current_user.email
    @wiki_id = params[:wiki_id]
    @q = "%#{params[:query]}%"
    unless Collaboration.all.count == 0
      Collaboration.all.each do |user|
        current_collaborator_emails << User.find_by(id: user[:user_id]).email
      end
    end
    current_collaborator_emails.uniq!
    @user = User.where("email LIKE ?", @q).where.not(email: current_collaborator_emails)
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
     @wiki = current_user.wikis.new(wiki_params)
     authorize @wiki


     if @wiki.save
       redirect_to @wiki, notice: "The wiki was saved successfully."
     else
       flash.now[:alert] = "Error creating article. Please try again."
       render :new
     end
   end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.update(wiki_params)
       redirect_to @wiki, notice: "The wiki was saved successfully."
     else
       flash.now[:alert] = "Error creating article. Please try again."
       render :new
     end
   end

   def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki

     if @wiki.destroy
       flash[:alert] = "The article has been destroyed"
     else
       flash[:notice] = "Unable to delete the article"
     end

     redirect_to root_path
   end



  private

  def wiki_params
    params.require(:wiki).permit(:title,:body,:private)
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper


  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/downgrades_helper.rb
module DowngradesHelper

end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborations/delete.html.erb
<h1>Collaborations#delete</h1>
<p>Find me in app/views/collaborations/delete.html.erb</p>

app/views/collaborations/edit.html.erb
<%= form_tag(collaboration_path, :method => :delete) do %>
<%= hidden_field_tag :id %>
<div class="row">
  <div class="col-md-5">
    <h2>List of Collaborators</h2>
    <% @colabs.each do |c| %>
      <div class="media">
        <div class="media-body">
          <h4 class="pull-left">
            <%= user = User.find_by(id: c.user_id).email %>
            <%= check_box_tag 'selected_emails[]', user -%>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= submit_tag %>
<% end %>
<%= params %>

app/views/collaborations/new.html.erb
<%= @wiki_id %>
<%= @user_id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>
    <header class='page-header'>
      <h1>Blocipedia</h1>
      <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </header>
    <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
    <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search_suggestions/new.html.erb
<%= form_tag('/collaborations') do %>
<%= hidden_field_tag :wiki_id, @wiki_id %>
<div class="row">
  <div class="col-md-5">
    <h2>List of Collaborators</h2>
    <% @user.each do |u| %>
      <div class="media">
        <div class="media-body">
          <h4 class="pull-left">
            <%= u.email %>
            <%= check_box_tag 'selected_emails[]', u.email -%>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= submit_tag %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% flash[:notice] = f.object.errors.full_messages.join(",\n ") if f.object.errors.any? %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter the body" %>
  </div>
 <% if current_user.admin? || (current_user.premium? && (current_user.id == @wiki.user_id || new_view )) %>
   <div class="form-group">
     <%= f.label :private, class: 'checkbox' do %>
     <%= f.check_box :private %> Private wiki
   <% end %>
   </div>
 <% end %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit The Article</h1>

<div class="row">
  <div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>List of Wiki Articles</h1>

<%= link_to "Create an article", new_wiki_path, class: 'btn btn-info' %>
<div class="row">
  <div class="col-md-8">
    <% if @wikis.select { |p| (p.private && (p.user_id == current_user.id || current_user.admin?)) || p.collaborations.where(user_id: current_user.id).exists? }.count > 0 %>
      <h3>Private and Collaborated Wikis:</h3>
      <% @wikis.select { |p| (p.private && (p.user_id == current_user.id || current_user.admin?)) || p.collaborations.where(user_id: current_user.id).exists? }.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
      <% end %>
    <h3>Public Wikis:</h3>
    <% end %>

    <% @wikis.select { |p| !p.private }.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %>
        </h4>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Create Wiki Article</h1>

<div class="row">
  <div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki, new_view: true } %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h3><%= @wiki.title %></h3>
<div class="row">
  <div class="col-md-9">
      <%= markdown(@wiki.body) %>
  </div>
  <div class="col-md-3">
    <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-warning' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this article?' } %>
    <% if (@wiki.private && (current_user.premium? || current_user.admin?)) %>
      <h6>For possible collaboration on the article, you can search users by email:</h6>
      <%= form_tag :new_search_suggestion, method: :get do %>
        <%= hidden_field_tag :wiki_id, @wiki.id %>
        <input class="seach full width" id="searchbar" name="query" placeholder="Search User by Email" type="text"
        autocomplete="off">
      <% end %>


      <br>
        <%= link_to "Remove Collaborators", edit_collaboration_path, class: 'btn btn-info' %>
      </br>
    <% end %>
</div>

<br>
    <%= link_to "Return", root_path, class: 'glyphicon glyphicon-circle-arrow-left' %>
</br>